### PR TITLE
PF Calculator

### PR DESCRIPTION
**Pull request by omerbaa**
Pull request overview
---------------------

### CODE REVIEW

**Comment by omerbaa** [comment]
#716 
#719

**Review by nbintertech — CHANGES_REQUESTED** [review]
Math and inputs/outputs, everything looks as it was outlined in issue.

asking for 2 changes:
1. The water assessment bindings and logic should be part of /water and WaterAssessment, not PHAST. Sorry for the confusion there - I meant that they were accessed like PHAST, not part of it.
2.  Once we can fix tests and merge into develop, it would be helpful if PF-calculator code and Water are in 2 different branches and PRs

**Comment by omerbaa** [comment]
Moved water assessment to its own files (wasm)

**Comment by nbintertech** [comment]
Closing, split into two separate PRs

**Pull request closed without merging**
